name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: laravel_test
          MYSQL_USER: ${DB_USERNAME}
          MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Composer dependencies
        run: |
          curl -sS https://getcomposer.org/installer | php
          php composer.phar install --working-dir=src

      - name: Install npm dependencies
        run: |
          cd src
          npm install

      - name: Build frontend assets
        run: |
          cd src
          npm run production

      - name: Set up .env.testing
        run: |
          cp src/.env.example src/.env.testing
          echo "APP_ENV=testing" >> src/.env.testing
          echo "DB_CONNECTION=mysql" >> src/.env.testing
          echo "DB_HOST=127.0.0.1" >> src/.env.testing
          echo "DB_PORT=3306" >> src/.env.testing
          echo "DB_DATABASE=laravel_test" >> src/.env.testing
          echo "DB_USERNAME=laravel_user" >> src/.env.testing
          echo "DB_PASSWORD=laravel_pass" >> src/.env.testing

      - name: Generate app key
        run: |
          cd src
          php artisan key:generate --env=testing

      - name: Run migrations
        run: |
          cd src
          php artisan migrate --env=testing --force

      - name: Run tests
        run: |
          cd src
          php artisan test
