name:  Deploy Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.EC2_SERVER_IP }}
          USERNAME: ${{ secrets.EC2_USERNAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -i private_key.pem \
            -o StrictHostKeyChecking=no \
            -o ServerAliveInterval=60 \
            $USERNAME@$SERVER_IP << 'EOF'
            cd furima
            git pull origin main
            sudo docker-compose up -d --build
            sleep 10
            sudo docker-compose exec php bash -c "
              composer install &&
              npm install &&
              npm run production &&
              php artisan migrate --force &&
              php artisan config:cache &&
              php artisan route:cache &&
              php artisan view:cache
            "
          EOF
          