name:  Deploy Pipeline

on:
  push:
    branches:
      - main  # mainブランチへのpushでトリガーされる
  pull_request:
    branches:
      - main  # pull requestがmainブランチに対して行われた時
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.EC2_SERVER_IP }}
          USERNAME: ${{ secrets.EC2_USERNAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -i private_key.pem -o StrictHostKeyChecking=no $USERNAME@$SERVER_IP << 'EOF'
            cd furima
            git pull origin main
            sudo docker-compose down
            sudo docker-compose up -d --build
            docker-compose exec -T php bash -c '
            docker-compose exec -T php composer install
            docker-compose exec -T php npm install
            docker-compose exec -T php npm run production
            docker-compose exec -T php php artisan migrate --force
            docker-compose exec -T php php artisan config:cache
            docker-compose exec -T php php artisan route:cache
            docker-compose exec -T php php artisan view:cache
          EOF
